<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dmek8rU' shared service.

return $this->privates['.service_locator.dmek8rU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'compteRepository' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'compteRepository' => 'App\\Repository\\CompteRepository',
    'entityManager' => '?',
]);
