<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qIXff7_' shared service.

return $this->privates['.service_locator.qIXff7_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ProfilRepository' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'ProfilRepository' => 'App\\Repository\\ProfilRepository',
    'serializer' => '?',
]);
