<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VM7a3RK' shared service.

return $this->privates['.service_locator.VM7a3RK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'TransactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
    'UtilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'TransactionRepository' => 'App\\Repository\\TransactionRepository',
    'UtilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
    'serializer' => '?',
]);
