<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yQTOc5p' shared service.

return $this->privates['.service_locator.yQTOc5p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commissionRepository' => ['privates', 'App\\Repository\\CommissionRepository', 'getCommissionRepositoryService.php', true],
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'commissionRepository' => 'App\\Repository\\CommissionRepository',
    'entityManager' => '?',
]);
