<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kYGXC6k' shared service.

return $this->privates['.service_locator.kYGXC6k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteDepotController::Update' => ['privates', '.service_locator.n63jPxA', 'get_ServiceLocator_N63jPxAService.php', true],
    'App\\Controller\\CompteDepotController::UpdateCompte' => ['privates', '.service_locator.bU5WbX_', 'get_ServiceLocator_BU5WbXService.php', true],
    'App\\Controller\\CompteDepotController::UpdateDepot' => ['privates', '.service_locator.hIMNJyo', 'get_ServiceLocator_HIMNJyoService.php', true],
    'App\\Controller\\CompteDepotController::UpdatePartenaire' => ['privates', '.service_locator.EEnNkzT', 'get_ServiceLocator_EEnNkzTService.php', true],
    'App\\Controller\\CompteDepotController::creerCompte' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\CompteDepotController::faireDepot' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteDepotController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\FilRougeController::ajout' => ['privates', '.service_locator.sQJpPfG', 'get_ServiceLocator_SQJpPfGService.php', true],
    'App\\Controller\\FilRougeController::login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\FilRougeController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\TransactionController::envoyerArgent' => ['privates', '.service_locator.a2nNogn', 'get_ServiceLocator_A2nNognService.php', true],
    'App\\Controller\\TransactionController::retraitArgent' => ['privates', '.service_locator.yQTOc5p', 'get_ServiceLocator_YQTOc5pService.php', true],
    'App\\Controller\\CompteDepotController:Update' => ['privates', '.service_locator.n63jPxA', 'get_ServiceLocator_N63jPxAService.php', true],
    'App\\Controller\\CompteDepotController:UpdateCompte' => ['privates', '.service_locator.bU5WbX_', 'get_ServiceLocator_BU5WbXService.php', true],
    'App\\Controller\\CompteDepotController:UpdateDepot' => ['privates', '.service_locator.hIMNJyo', 'get_ServiceLocator_HIMNJyoService.php', true],
    'App\\Controller\\CompteDepotController:UpdatePartenaire' => ['privates', '.service_locator.EEnNkzT', 'get_ServiceLocator_EEnNkzTService.php', true],
    'App\\Controller\\CompteDepotController:creerCompte' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\CompteDepotController:faireDepot' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteDepotController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\FilRougeController:ajout' => ['privates', '.service_locator.sQJpPfG', 'get_ServiceLocator_SQJpPfGService.php', true],
    'App\\Controller\\FilRougeController:login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\FilRougeController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\TransactionController:envoyerArgent' => ['privates', '.service_locator.a2nNogn', 'get_ServiceLocator_A2nNognService.php', true],
    'App\\Controller\\TransactionController:retraitArgent' => ['privates', '.service_locator.yQTOc5p', 'get_ServiceLocator_YQTOc5pService.php', true],
], [
    'App\\Controller\\CompteDepotController::Update' => '?',
    'App\\Controller\\CompteDepotController::UpdateCompte' => '?',
    'App\\Controller\\CompteDepotController::UpdateDepot' => '?',
    'App\\Controller\\CompteDepotController::UpdatePartenaire' => '?',
    'App\\Controller\\CompteDepotController::creerCompte' => '?',
    'App\\Controller\\CompteDepotController::faireDepot' => '?',
    'App\\Controller\\CompteDepotController::setViewHandler' => '?',
    'App\\Controller\\FilRougeController::ajout' => '?',
    'App\\Controller\\FilRougeController::login' => '?',
    'App\\Controller\\FilRougeController::setViewHandler' => '?',
    'App\\Controller\\TransactionController::envoyerArgent' => '?',
    'App\\Controller\\TransactionController::retraitArgent' => '?',
    'App\\Controller\\CompteDepotController:Update' => '?',
    'App\\Controller\\CompteDepotController:UpdateCompte' => '?',
    'App\\Controller\\CompteDepotController:UpdateDepot' => '?',
    'App\\Controller\\CompteDepotController:UpdatePartenaire' => '?',
    'App\\Controller\\CompteDepotController:creerCompte' => '?',
    'App\\Controller\\CompteDepotController:faireDepot' => '?',
    'App\\Controller\\CompteDepotController:setViewHandler' => '?',
    'App\\Controller\\FilRougeController:ajout' => '?',
    'App\\Controller\\FilRougeController:login' => '?',
    'App\\Controller\\FilRougeController:setViewHandler' => '?',
    'App\\Controller\\TransactionController:envoyerArgent' => '?',
    'App\\Controller\\TransactionController:retraitArgent' => '?',
]);
