<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.a2nNogn' shared service.

return $this->privates['.service_locator.a2nNogn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'commissionRepository' => ['privates', 'App\\Repository\\CommissionRepository', 'getCommissionRepositoryService.php', true],
], [
    'commissionRepository' => 'App\\Repository\\CommissionRepository',
]);
