<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jZyqizD' shared service.

return $this->privates['.service_locator.jZyqizD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'compteRepository' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'partenaireRepository' => ['privates', 'App\\Repository\\PartenaireRepository', 'getPartenaireRepositoryService.php', true],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'profilRepository' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService.php', true],
    'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
], [
    'compteRepository' => 'App\\Repository\\CompteRepository',
    'partenaireRepository' => 'App\\Repository\\PartenaireRepository',
    'passwordEncoder' => '?',
    'profilRepository' => 'App\\Repository\\ProfilRepository',
    'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
]);
