<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zIvim80' shared service.

return $this->privates['.service_locator.zIvim80'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteDepotController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\FilRougeController::NewProfil' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\FilRougeController::ajout' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\FilRougeController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\CompteDepotController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\FilRougeController:NewProfil' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\FilRougeController:ajout' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\FilRougeController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\CompteDepotController::setViewHandler' => '?',
    'App\\Controller\\FilRougeController::NewProfil' => '?',
    'App\\Controller\\FilRougeController::ajout' => '?',
    'App\\Controller\\FilRougeController::setViewHandler' => '?',
    'App\\Controller\\CompteDepotController:setViewHandler' => '?',
    'App\\Controller\\FilRougeController:NewProfil' => '?',
    'App\\Controller\\FilRougeController:ajout' => '?',
    'App\\Controller\\FilRougeController:setViewHandler' => '?',
]);
