<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4l.UGwp' shared service.

return $this->privates['.service_locator.4l.UGwp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteDepotController::Update' => ['privates', '.service_locator.EQXRfz.', 'get_ServiceLocator_EQXRfz_Service.php', true],
    'App\\Controller\\CompteDepotController::creerCompte' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\CompteDepotController::faireDepot' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteDepotController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\FilRougeController::ajout' => ['privates', '.service_locator.sQJpPfG', 'get_ServiceLocator_SQJpPfGService.php', true],
    'App\\Controller\\FilRougeController::login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\FilRougeController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\CompteDepotController:Update' => ['privates', '.service_locator.EQXRfz.', 'get_ServiceLocator_EQXRfz_Service.php', true],
    'App\\Controller\\CompteDepotController:creerCompte' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\CompteDepotController:faireDepot' => ['privates', '.service_locator.JfrEn5y', 'get_ServiceLocator_JfrEn5yService.php', true],
    'App\\Controller\\CompteDepotController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\FilRougeController:ajout' => ['privates', '.service_locator.sQJpPfG', 'get_ServiceLocator_SQJpPfGService.php', true],
    'App\\Controller\\FilRougeController:login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\FilRougeController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\CompteDepotController::Update' => '?',
    'App\\Controller\\CompteDepotController::creerCompte' => '?',
    'App\\Controller\\CompteDepotController::faireDepot' => '?',
    'App\\Controller\\CompteDepotController::setViewHandler' => '?',
    'App\\Controller\\FilRougeController::ajout' => '?',
    'App\\Controller\\FilRougeController::login' => '?',
    'App\\Controller\\FilRougeController::setViewHandler' => '?',
    'App\\Controller\\CompteDepotController:Update' => '?',
    'App\\Controller\\CompteDepotController:creerCompte' => '?',
    'App\\Controller\\CompteDepotController:faireDepot' => '?',
    'App\\Controller\\CompteDepotController:setViewHandler' => '?',
    'App\\Controller\\FilRougeController:ajout' => '?',
    'App\\Controller\\FilRougeController:login' => '?',
    'App\\Controller\\FilRougeController:setViewHandler' => '?',
]);
