<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EQXRfz.' shared service.

return $this->privates['.service_locator.EQXRfz.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'user' => ['privates', '.errored..service_locator.EQXRfz..App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.EQXRfz.": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
], [
    'user' => 'App\\Entity\\Utilisateur',
]);
