<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYgGiD4V\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYgGiD4V/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYgGiD4V.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYgGiD4V\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYgGiD4V\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YgGiD4V',
    'container.build_id' => '651367a7',
    'container.build_time' => 1565172410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYgGiD4V');
