<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMAoqfDt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMAoqfDt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMAoqfDt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMAoqfDt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMAoqfDt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MAoqfDt',
    'container.build_id' => '3fd2111e',
    'container.build_time' => 1566143654,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMAoqfDt');
