<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLYt5K2Y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLYt5K2Y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLYt5K2Y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLYt5K2Y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLYt5K2Y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LYt5K2Y',
    'container.build_id' => '58932724',
    'container.build_time' => 1565293058,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLYt5K2Y');
